export default {
  login: "chinmaydey",
  id: 39548443,
  node_id: "MDQ6VXNlcjM5NTQ4NDQz",
  avatar_url: "https://avatars.githubusercontent.com/u/39548443?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/chinmaydey",
  html_url: "https://github.com/chinmaydey",
  followers_url: "https://api.github.com/users/chinmaydey/followers",
  following_url:
    "https://api.github.com/users/chinmaydey/following{/other_user}",
  gists_url: "https://api.github.com/users/chinmaydey/gists{/gist_id}",
  starred_url: "https://api.github.com/users/chinmaydey/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/chinmaydey/subscriptions",
  organizations_url: "https://api.github.com/users/chinmaydey/orgs",
  repos_url: "https://api.github.com/users/chinmaydey/repos",
  events_url: "https://api.github.com/users/chinmaydey/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/chinmaydey/received_events",
  type: "User",
  site_admin: false,
  name: "Chinmay Dey",
  company: "National Australia Bank",
  blog: "MyBlog",
  location: "Melbourne",
  email: null,
  hireable: null,
  bio: "Developer by Heart.",
  twitter_username: "chinmaydey",
  public_repos: 3,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2018-05-23T06:36:54Z",
  updated_at: "2021-03-17T09:44:43Z",
};
